{
  PerkOverhaul - Phase 2 Value Changes
  Generated by mnehmos.fnvedit.mcp

  This script modifies the actual gameplay effect values (EPFD floats)
  for perks that use Entry Point effects. Run on PerkOverhaul.esp PERK records.

  Changes:
    BloodyMess:       1.05x -> 1.10x damage
    Toughness:        +3/+6 DT -> +4/+8 DT
    DemolitionExpert: 1.2/1.4/1.6x -> 1.25/1.50/1.75x
    Educated:         +2 -> +3 skill points/level
    SwiftLearner:     1.1/1.2/1.3x -> 1.15/1.30/1.45x XP
    FastMetabolism:   1.2x -> 1.35x stimpak healing (if Entry Point)
}

unit PerkOverhaulValues;

var
  changeCount: Integer;

function Initialize: Integer;
begin
  Result := 0;
  changeCount := 0;
  AddMessage('[PerkOverhaul] Phase 2: Modifying effect values...');
end;

function SetEPFDFloat(effect: IInterface; newValue: Double): Boolean;
var
  epfd: IInterface;
begin
  Result := False;
  epfd := ElementBySignature(effect, 'EPFD');
  if Assigned(epfd) then begin
    SetNativeValue(epfd, newValue);
    Result := True;
  end;
end;

function Process(e: IInterface): Integer;
var
  sig, edid: string;
  effects, effect, epfd: IInterface;
  i, count: Integer;
  oldVal: Double;
begin
  Result := 0;
  sig := Signature(e);
  if sig <> 'PERK' then Exit;

  edid := EditorID(e);
  effects := ElementByName(e, 'Effects');
  if not Assigned(effects) then Exit;
  count := ElementCount(effects);

  // ── BloodyMess: 1.05 -> 1.10 (effect index 1) ──
  if SameText(edid, 'BloodyMess') then begin
    if count > 1 then begin
      effect := ElementByIndex(effects, 1);
      if SetEPFDFloat(effect, 1.10) then begin
        AddMessage('  BloodyMess: damage multiplier 1.05 -> 1.10');
        Inc(changeCount);
      end;
    end;
  end;

  // ── Toughness: +3/+6 -> +4/+8 ──
  if SameText(edid, 'Toughness') then begin
    for i := 0 to Pred(count) do begin
      effect := ElementByIndex(effects, i);
      epfd := ElementBySignature(effect, 'EPFD');
      if Assigned(epfd) then begin
        oldVal := GetNativeValue(epfd);
        if (oldVal > 2.9) and (oldVal < 3.1) then begin
          SetNativeValue(epfd, 4.0);
          AddMessage('  Toughness Rank 1: DT +3 -> +4');
          Inc(changeCount);
        end;
        if (oldVal > 5.9) and (oldVal < 6.1) then begin
          SetNativeValue(epfd, 8.0);
          AddMessage('  Toughness Rank 2: DT +6 -> +8');
          Inc(changeCount);
        end;
      end;
    end;
  end;

  // ── DemolitionExpert: 1.2/1.4/1.6 -> 1.25/1.50/1.75 ──
  if SameText(edid, 'DemolitionExpert') then begin
    for i := 0 to Pred(count) do begin
      effect := ElementByIndex(effects, i);
      epfd := ElementBySignature(effect, 'EPFD');
      if Assigned(epfd) then begin
        oldVal := GetNativeValue(epfd);
        if (oldVal > 1.19) and (oldVal < 1.21) then begin
          SetNativeValue(epfd, 1.25);
          AddMessage('  DemolitionExpert Rank 1: 1.20x -> 1.25x');
          Inc(changeCount);
        end;
        if (oldVal > 1.39) and (oldVal < 1.41) then begin
          SetNativeValue(epfd, 1.50);
          AddMessage('  DemolitionExpert Rank 2: 1.40x -> 1.50x');
          Inc(changeCount);
        end;
        if (oldVal > 1.59) and (oldVal < 1.61) then begin
          SetNativeValue(epfd, 1.75);
          AddMessage('  DemolitionExpert Rank 3: 1.60x -> 1.75x');
          Inc(changeCount);
        end;
      end;
    end;
  end;

  // ── Educated: +2 -> +3 skill points per level ──
  if SameText(edid, 'Educated') then begin
    for i := 0 to Pred(count) do begin
      effect := ElementByIndex(effects, i);
      epfd := ElementBySignature(effect, 'EPFD');
      if Assigned(epfd) then begin
        oldVal := GetNativeValue(epfd);
        if (oldVal > 1.9) and (oldVal < 2.1) then begin
          SetNativeValue(epfd, 3.0);
          AddMessage('  Educated: +2 -> +3 skill points/level');
          Inc(changeCount);
        end;
      end;
    end;
  end;

  // ── SwiftLearner: 1.1/1.2/1.3 -> 1.15/1.30/1.45 XP ──
  if SameText(edid, 'SwiftLearner') then begin
    for i := 0 to Pred(count) do begin
      effect := ElementByIndex(effects, i);
      epfd := ElementBySignature(effect, 'EPFD');
      if Assigned(epfd) then begin
        oldVal := GetNativeValue(epfd);
        if (oldVal > 1.09) and (oldVal < 1.11) then begin
          SetNativeValue(epfd, 1.15);
          AddMessage('  SwiftLearner Rank 1: 1.10x -> 1.15x XP');
          Inc(changeCount);
        end;
        if (oldVal > 1.19) and (oldVal < 1.21) then begin
          SetNativeValue(epfd, 1.30);
          AddMessage('  SwiftLearner Rank 2: 1.20x -> 1.30x XP');
          Inc(changeCount);
        end;
        if (oldVal > 1.29) and (oldVal < 1.31) then begin
          SetNativeValue(epfd, 1.45);
          AddMessage('  SwiftLearner Rank 3: 1.30x -> 1.45x XP');
          Inc(changeCount);
        end;
      end;
    end;
  end;

end;

function Finalize: Integer;
begin
  Result := 0;
  AddMessage('[PerkOverhaul] Phase 2 complete: ' + IntToStr(changeCount) + ' values changed');
end;

end.
